name: sandbox-env
channels:
  - gimli
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.2.0=h9c3ff4c_2
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_2
  - boost=1.76.0=py39h5472131_1
  - boost-cpp=1.76.0=h312852a_1
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py39hf3d152e_1
  - cftime=1.5.1.1=py39hce5d2b2_1
  - curl=7.80.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - double-conversion=3.1.6=h9c3ff4c_0
  - eigen=3.4.0=h4bd325d_0
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.4.0=h6987444_5
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.28.3=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - gcc_impl_linux-64=11.2.0=h82a94d6_11
  - gcc_linux-64=11.2.0=h39a9532_2
  - gettext=0.19.8.1=h73d1719_1008
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.70.2=h780b84a_0
  - glib-tools=2.70.2=h780b84a_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.18.5=hf529b03_2
  - gstreamer=1.18.5=h9f60fe5_2
  - gxx_impl_linux-64=11.2.0=h82a94d6_11
  - gxx_linux-64=11.2.0=hacbe6df_2
  - h5py=3.6.0=nompi_py39h7e08c79_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_103
  - icu=68.2=h9c3ff4c_0
  - imageio=2.13.2=pyh239f2a4_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_metadata=4.8.2=hd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - jsoncpp=1.9.4=h4bd325d_3
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.80.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=11.2.0=h0952999_11
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.2=h174f98d_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.5=hd57d9b9_1
  - libsanitizer=11.2.0=he4da1e4_11
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=11.2.0=h0952999_11
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h36c2ea0_1013
  - loguru=0.5.3=py39hf3d152e_3
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.0=py39hf3d152e_0
  - matplotlib-base=3.5.0=py39h2fa2bec_0
  - metis=5.1.0=h58526e2_1006
  - more-itertools=8.12.0=pyhd8ed1ab_0
  - mpfr=4.1.0=h9202a9a_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.27=ha770c72_1
  - mysql-libs=8.0.27=hfa10184_1
  - ncurses=6.2=h58526e2_4
  - netcdf4=1.5.8=nompi_py39h64b754b_101
  - nettle=3.6=he412f7d_0
  - npx=0.0.24=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.73=hb5efdd6_0
  - numpy=1.21.4=py39hdbf815f_0
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.3.18=pthreads_h4748800_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pgcore=1.2.2=np121py39h3fd9d12_0
  - pillow=8.4.0=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py39hf3d152e_2
  - proj=8.2.0=h277dcde_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.11.4=h9c3ff4c_0
  - py=1.11.0=pyh6c4a22f_0
  - pygimli=1.2.2=py_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pytest=6.2.5=py39hf3d152e_1
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - scipy=1.7.3=py39hee8e79c_0
  - scooby=0.5.9=pyhd8ed1ab_0
  - setuptools=59.4.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - suitesparse=5.10.1=h9e50725_1
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.4.0=h4bd325d_1
  - tbb-devel=2021.4.0=h4bd325d_1
  - tetgen=1.6.0=he1b5a44_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_2
  - tzdata=2021e=he74cb21_0
  - utfcpp=3.2.1=ha770c72_0
  - vtk=9.1.0=no_osmesa_py39hc049222_102
  - wheel=0.37.0=pyhd8ed1ab_1
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h4bd325d_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - alabaster==0.7.12
    - argon2-cffi==21.2.0
    - argon2-cffi-bindings==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - bokeh==2.4.2
    - cffi==1.15.0
    - charset-normalizer==2.0.9
    - colorama==0.4.4
    - cython==0.29.25
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - docutils==0.17.1
    - entrypoints==0.3
    - gempy==2.2.10
    - idna==3.3
    - imagesize==1.3.0
    - ipykernel==6.6.0
    - ipython==7.30.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - jsonschema==4.2.1
    - jupyter==1.0.0
    - jupyter-client==7.1.0
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - meshio==4.4.6
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nbsphinx==0.8.7
    - nest-asyncio==1.5.4
    - networkx==2.6.3
    - notebook==6.4.6
    - opencv-contrib-python==4.5.4.60
    - pandas==1.3.4
    - pandocfilters==1.5.0
    - panel==0.12.5
    - param==1.12.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pooch==1.5.2
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.23
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pyct==0.4.8
    - pygments==2.10.0
    - pyrsistent==0.18.0
    - pysolar==0.10
    - pytz==2021.3
    - pyvista==0.32.1
    - pyvistaqt==0.5.0
    - pyviz-comms==2.1.0
    - pywavelets==1.2.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.1
    - qtpy==1.11.3
    - requests==2.26.0
    - scikit-image==0.19.0
    - seaborn==0.11.2
    - send2trash==1.8.0
    - snowballstemmer==2.2.0
    - sphinx==4.3.1
    - sphinx-copybutton==0.4.0
    - sphinx-markdown-tables==0.0.15
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - terminado==0.12.1
    - testpath==0.5.0
    - theano==1.0.5
    - tifffile==2021.11.2
    - tqdm==4.62.3
    - traitlets==5.1.1
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
prefix: /home/daniel/anaconda3/envs/sandbox-env
